apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-k8s-deployment-v1
  labels:
    commit: ${GIT_COMMIT}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-k8s-deployment
  template:
    metadata:
      labels:
        app: cloud-k8s-deployment
        commit: ${GIT_COMMIT}
        color: blue
    spec:
      containers:
      - name: cloud-k8s-deployment
        image: iad.ocir.io/oraclemetodista/ocir-repo/cloudnative:${GIT_COMMIT}
        imagePullPolicy: Always
        ports:
        - name: cloud-k8s-deployment
          containerPort: 8080
          protocol: TCP
        volumeMounts:
          - name: podinfo
            mountPath: /tmp
            readOnly: false
      volumes:
        - name: podinfo
          downwardAPI:
            items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels 
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-k8s-deployment
  labels:
    app: cloud-k8s-deployment
    commit: ${GIT_COMMIT}
spec:
  ports:
  - port: 30000
    targetPort: 8080
  selector:
    app: cloud-k8s-deployment
    color: blue
  type: ClusterIP
---
